# Header
menu:
  主页: /
  所有文章: /archives
  #相册: /photos
  #随笔: /tags/随笔
  #成长: /tags/成长
  

# SubNav
subnav:
  github: "https://github.com/xiachengwei5"
  weibo: "http://weibo.com/xiachengwei5"
  mail: "mailto:xiachengwei5@163.com"
  jianshu: "http://www.jianshu.com/u/a31d9187f8ff"

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content
excerpt_link: 'more'
show_all_link: '展开全文'
fancybox: true
mathjax: false


# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
reward_wording: '喜欢就点赞，疼爱就打赏'
alipay: http://olywxnzqu.bkt.clouddn.com/img/hexo_index/logo.png
weixin: http://olywxnzqu.bkt.clouddn.com/img/hexo_index/logo.png

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# 是否在新窗口打开链接
open_in_new: false



# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: http://olywxnzqu.bkt.clouddn.com/img/hexo_index/logo.png

#你的头像url
avatar: "http://olywxnzqu.bkt.clouddn.com/img/hexo_index/logo.png"


#是否开启分享
# share_jia: true

mobile:
  social: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus 不需要使用某项，直接设置值为false，或注释掉
#请参考wiki：

#1、多说
#duoshuo: "litten-hexo"

#2、网易云跟帖
#wangyiyun: '2dba06fbf8d24c13915ea6c6aa7183b1'

#3、畅言
changyan_appid: 'cyteTBtB5'
changyan_conf: '374815d88e087876ec6934554affdc30'

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
#disqus: false

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: false
  aboutme: '关于我'

friends:
  Myron: http://www.myronliu.com
  Devzeng: http://www.devzeng.com
  Heji: https://heji1993.github.io
  litten: http://litten.me
  sentsin: http://sentsin.com
  MOxFIVE: http://moxfive.xyz
  w3cplus: http://www.w3cplus.com
  掘金: https://gold.xitu.io
  阮一峰: http://www.ruanyifeng.com
  廖雪峰: https://www.liaoxuefeng.com/
  伍迷家园: http://www.cnblogs.com/cj723/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 动如脱兔，静如止水